# Generated by Django 2.2 on 2019-04-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AlterField(
            model_name='post',
            name='user_name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
